version: '3'
services:
  zookeeper-kafka:
    hostname: zookeeper-kafka
    container_name: zookeeper-kafka
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - api-b3-net
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-kafka:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - api-b3-net

networks:
  api-b3-net:
    driver: bridge

