version: '3'

services:
  postgres-pipeline:
    hostname: postgres-acao-b3
    container_name: postgres-pipeline
    image: postgres
    shm_size: 4gb
    environment:
      POSTGRES_PASSWORD: "Postgres2020!"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - api-b3-net

networks:
  api-b3-net:
    driver: bridge
